sudo: false
cache:
directories:
- $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "3.10"
      env: TOXENV=py310
    - python: "3.11"
      env: TOXENV=py311
    - python: "pypy-3.10"
      env: TOXENV=pypy
    - python: "3.10"
      env: TOXENV=packaging


install:
  - "pip install -r requirements-test.txt"

script:
  - tox


before_install:
  - pip install codecov coverage


after_success:
  - tox -e coverage-report
  - COVERAGE_FILE=.tox/.coverage coverage xml
  - codecov -f coverage.xml
