name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.10'
            tox-env: py310
          - python-version: '3.11'
            tox-env: py311
          - python-version: 'pypy-3.10'
            tox-env: pypy
          - python-version: '3.10'
            tox-env: packaging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run tox
        run: tox -e ${{ matrix.tox-env }}
